driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_image: chef/chef
  chef_version: current

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
- name: centos-5
  driver:
    image: centos:5

- name: centos-6
  driver:
    image: centos:6

- name: centos-7
  driver:
    image: centos:7

- name: oracle-7
  driver:
    image: oraclelinux:7

suites:
- name: connectors
  run_list:
  - recipe[yum-mysql-community::connectors]
  attributes: {}
- name: mysql55
  run_list:
  - recipe[yum-mysql-community::mysql56]
- name: mysql56
  run_list:
  - recipe[yum-mysql-community::mysql56]
  attributes: {}

- name: mysql57
  run_list:
  - recipe[yum-mysql-community::mysql57]
  attributes: {}
