default['git_drupal']['root_directory'] = 'smith_wesson_stage'
default['git_drupal']['web_directory'] = '/var/www/html'
default['git_drupal']['git_base_command'] = 'git'
default['git_drupal']['git_checkout_command'] = 'checkout'
default['git_drupal']['git_switched_branch'] = 'dev'
default['git_drupal']['git_master_branch'] = 'master'
default['git_drupal']['git_branch'] = 'branch'
default['git_drupal']['date'] = 'date'
default['git_drupal'][''] = ''
default['git_drupal'][''] = ''
default['git_drupal'][''] = ''
default['git_drupal'][''] = ''
default['git_drupal'][''] = ''

