default['patch_auto']['server1'] = '13.68.215.122'
default['patch_auto']['server2'] = 'ubuntupatchtest'
default['patch_auto']['server3'] = 'ubuntupatchprod'
default['patch_auto']['new_feature'] = 'test-patchbranch'
default['patch_auto']['branch'] = 'test-patchbranch'
default['patch_auto']['commit'] = 'Initial commit to new changes'
